### ISSUE TITLE
Simplified usage

### ISSUE THREAD

**Issue by tivnet** [slaFFik/wp-requirements#20]
A static method that receives the same parameters as the constructor, creates the object, does all processing and exits, returning `bool` of the validation.

**Comment by slaFFik** [comment]
How is that different from this?

``` php
$requirement = new WP_Requirement();
$requirement->valid()
```

Not sure, why does anyone need a one line `WP_Requirement::init()->valid()` instead of 2 lines. That just adds 1 more point of failure to the class with no benefit.

**Comment by tivnet** [comment]
Something like:

``` php
if ( ! WP_Requirements::met( __FILE__ ) ) {
    return;
}
```
