### ISSUE TITLE
Default action: nothing? Or notice.

### ISSUE THREAD

**Issue by tivnet** [slaFFik/wp-requirements#21]
https://github.com/slaFFik/wp-requirements/blob/f89eaa9416040d7e89163eef568e82f4f7d86205/wp-requirements.php#L73

I believe, deactivating by default is wrong. Should be no action or maybe only the notice.

**Comment by slaFFik** [comment]
Plugin can cause damage to the site if it is not deactivated when not meeting requirements. White screen of death etc.
I believe, deactivation be default is ok, and plugin developer when creating his `wp-requirements.json` file, can change the default behaviour. So I'm ok with leaving this as is.

**Comment by tivnet** [comment]
I am thinking about temporary deactivation of the main plugin (say WooCommerce) causing a cascade of deactivations of all dependants.
