### ISSUE TITLE
Checking for "any version"

### ISSUE THREAD

**Issue by tivnet** [slaFFik/wp-requirements#22]
It is possible today to check for any version of a plugin by leaving the version blank or `0`.
However, the message looks ugly.
Need to check if the version is blank and use a different message.

**Comment by slaFFik** [comment]
What's the point of such check?
If you want to check that this plugin is installed no matter which version - why not just check for any of its functions/classes? See #6

**Comment by tivnet** [comment]
That's two separate issues. This one is just a matter of tweaking the error message. Easy thing.

**Comment by slaFFik** [comment]
Ok, agree. After some thinking I start to see a value in different messages like "function _name doesn't exist" vs "plugin X of any version is not activated"

**Comment by tivnet** [comment]
bc28ef26bfc5d78b5b78857c49e22b08a181583e
