### ISSUE TITLE
Loading the latest version only?

### ISSUE THREAD

**Issue by tivnet** [slaFFik/wp-requirements#24]
Two options:
1. Give a new class name to each new major release. For instance, rename the class to `WP_Requirements_2` now. This means that any additional functionality will bump the major release. Not practical, probably.
2. Use a `hook` loading of the class (similar to `CMB2`).

**Comment by tivnet** [comment]
In the hook loading, still need to worry about the major version changes.

So, probably, we need both: class name matching the major release # and the hook loading.

@slaFFik If you confirm the `WP_Requirements_2` change, we should do it now before the `develop` is merged with `master`.

**Comment by tivnet** [comment]
How about keeping both the old `wp-requirements.php` and the new `wp-requirements-2.php` in the repository? Those who need and want to upgrade will modify their code. This should solve the backward incompatibility problems, because, with each major release, we'll make a new file and new class name.

► Still need the `hook` loading to get the latest minor release.

**Comment by slaFFik** [comment]
I agree with the arguments and a proposed solution here :)

**Comment by tivnet** [comment]
@slaFFik Please check the implementation and if OK, let's make it 2.0.0

Note that the old class is kept as-is.
