### ISSUE TITLE
Display the requirements that are not met in the error message.

### ISSUE THREAD

**Issue by BoweFrankema** [slaFFik/wp-requirements#7]
When an installation does not meet the requirements, the error message should print/display which requirements are not met. 

"WeFoster Plus can not be activated because your WordPress installation does **not** meet the following requirements:
Active Plugin: **BuddyPress v2.2**
PHP Version: **5.3**
"

**Comment by slaFFik** [comment]
Yeah, that's in to do list :)

**Comment by slaFFik** [comment]
Here is an example:

![2015-09-26 23 56 29](https://cloud.githubusercontent.com/assets/282234/10377219/c8e936b2-6e0a-11e5-8f19-db5bb1141c56.png)

The message will be more generic.

**Comment by BoweFrankema** [comment]
Love it!

**Comment by slaFFik** [comment]
Current status:

![2015-10-09 17 49 14](https://cloud.githubusercontent.com/assets/282234/10397018/2725fdde-6eae-11e5-823c-7749da5c2aa4.png)

Anything to add?
